In [5]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

In [6]:
G=nx.Graph()
G.add_edge(1,2)
G.add_edge(2,3)
print('#Node: %i, #Edge: %i' % (G.number_of_nodes(), G.number_of_edges()))
print('Has 3-4 edge: %s' % G.has_edge(3,4))
print(nx.to_numpy_array(G).T)
G.add_nodes_from(range(1,7))
G2=nx.Graph()
G2.add_edge(1,2, weight=3)
G2.add_edge(2,3,weight=2)
print(G2[2])

#Node: 3, #Edge: 2
Has 3-4 edge: False
[[0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]]
{1: {'weight': 3}, 3: {'weight': 2}}


### The equation of the cocitation network is

$$ C_{ij} = \sum^n_{k=1} A_{ik} A_{jk} $$

In [7]:
# Read the gml file
G = nx.read_gml("./proofwikidefs_la.gml", "name")
def cocitation(G):
    """ 
    The algorithm to compute the cocitation index based on graphical approach
    By graphical approach, which means that we need to use networkx package to compute the edges between each pair of nodes, to find out the similarity between certain pair of nodes.
    Input:
        graph
    Output:
        cocitation results
    """
    # G.predecessors will return the a directed edge from m to n
    # rational: we have a list of the m to n data, then we need to see if they have overlap.
    # Define CG
    CG = nx.Graph()

    for ind, i in enumerate(G.nodes):
        for j in list(G.nodes)[ind:]:
            co_weight = len([ele for ele in list(G.predecessors(i)) if ele in list(G.predecessors(i)) and ele in list(G.predecessors(j))])
            if co_weight > 0:
                CG.add_edge(i, j, weight = co_weight)
            else:
                CG.add_edge(i, j, weight = 0)
    return CG
        
# return G_cocitation
cocit_net = cocitation(G)


In [8]:
a = nx.to_numpy_array(G).T
C1 = np.dot(a, a.transpose())
C2 = nx.to_numpy_array(cocit_net).T
print(C1)
print(C2)
Cdiff = C1-C2
print(f"Diff between C1 and C2 is {Cdiff.sum().sum()}")

[[1. 0. 0. ... 0. 0. 0.]
 [0. 2. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 0. 0. ... 0. 0. 0.]
 [0. 2. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Diff between C1 and C2 is 4872.0
